import 'package:soilreport/src/localization/string_hardcoded.dart';

/// Base class for all all client-side errors that can be generated by the app

enum AlertWidgetType {
  dialog,
  snack
}

sealed class AppException implements Exception {
  AppException(this.code, this.message, this.type);
  final String code;
  final String message;
  final StackTrace stackTrace = StackTrace.current;
  final AlertWidgetType type;

  @override
  String toString() => message;
}

/// Auth

class PasswordNotMatchException extends AppException {

  PasswordNotMatchException()
      : super('password-not-match', 'Exception.PasswordNotMatch'.hardcoded, AlertWidgetType.snack);
}

class PasswordInvalidException extends AppException {

  PasswordInvalidException()
      : super('password-invalid', 'Exception.PasswordInvalid'.hardcoded, AlertWidgetType.snack);
}

class CouldntSetPasswordException extends AppException {

  CouldntSetPasswordException()
      : super('couldnt-set-password', 'Exception.CouldNotSetPassword'.hardcoded, AlertWidgetType.snack);
}

class WrongPhoneNumberException extends AppException {
  WrongPhoneNumberException()
      : super('wrong-phone-number', 'Exception.WrongPhoneNumber'.hardcoded, AlertWidgetType.snack);
}
class WrongOtpException extends AppException {
  WrongOtpException()
      : super('wrong-otp', 'Exception.WrongOtp'.hardcoded, AlertWidgetType.dialog);
}

class ClientStatsFetchFailedException extends AppException {
  ClientStatsFetchFailedException()
      : super('client-stats-fetch-failed', 'Exception.ClientStatsFetchFailed'.hardcoded, AlertWidgetType.dialog);
}
class UserNotFoundException extends AppException {
  UserNotFoundException() : super('user-not-found', 'Exception.UserNotFound'.hardcoded, AlertWidgetType.dialog);
}

class NetworkIssueException extends AppException {
  NetworkIssueException() : super('network-issue', 'Exception.NetworkIssue'.hardcoded, AlertWidgetType.snack);
}
class SystemErrorException extends AppException {
  final String? sysMessage;
  SystemErrorException({this.sysMessage}) : super("system-error-exception", sysMessage ?? 'Exception.SystemError'.hardcoded, AlertWidgetType.dialog);
}

class BiometricAuthenticationFailedException extends AppException {
    BiometricAuthenticationFailedException() : super("biometric-authentication-failed-exception", 'Exception.BiometricAuthenticationFailed'.hardcoded, AlertWidgetType.snack);
}
class BiometricAuthenticationNotSupportedException extends AppException {
    BiometricAuthenticationNotSupportedException() : super("biometric-authentication-not-supported-exception", 'Exception.BiometricAuthenticationNotSupported'.hardcoded, AlertWidgetType.snack);
}

class JsonParseException extends AppException {
  JsonParseException() : super('json-parse', 'Exception.JsonParse'.hardcoded, AlertWidgetType.dialog);
}

class ApiIssueException extends AppException {
  ApiIssueException() : super('api-issue', 'Exception.ApiIssue'.hardcoded, AlertWidgetType.dialog);
}

class UnauthorizedUserException extends AppException {
  UnauthorizedUserException() : super('unauthorized-user', 'Exception.UnauthorizedUser'.hardcoded, AlertWidgetType.dialog);
}

/// Profile-specific exceptions
class EmptyEmailException extends AppException {
  EmptyEmailException()
      : super('empty-email', 'Exception.EmptyEmail'.hardcoded, AlertWidgetType.snack);
}

class EmptyFullNameException extends AppException {
  EmptyFullNameException()
      : super('empty-full-name', 'Exception.EmptyFullName'.hardcoded, AlertWidgetType.snack);
}

class InvalidFullNameException extends AppException {
  InvalidFullNameException()
      : super('invalid-full-name', 'Exception.InvalidFullName'.hardcoded, AlertWidgetType.snack);
}

class InvalidEmailFormatException extends AppException {
  InvalidEmailFormatException()
      : super('invalid-email-format', 'Exception.InvalidEmailFormat'.hardcoded, AlertWidgetType.snack);
}

class EmailVerificationFailedException extends AppException {
  EmailVerificationFailedException()
      : super('email-verification-failed', 'Exception.EmailVerificationFailed'.hardcoded, AlertWidgetType.dialog);
}

class EmptyPhoneNumberException extends AppException {
  EmptyPhoneNumberException()
      : super('empty-phone-number', 'Exception.EmptyPhoneNumber'.hardcoded, AlertWidgetType.snack);
}

class CantReachServerException extends AppException {
  CantReachServerException() : super('cant-reach-server', 'Auth.Alert'.hardcoded, AlertWidgetType.dialog);
}   

class NoInternetConnectionException extends AppException {
  NoInternetConnectionException() : super('no-internet-connection', 'Auth.Alert'.hardcoded, AlertWidgetType.snack);
}

class InvalidPhoneNumberFormatException extends AppException {
  InvalidPhoneNumberFormatException()
      : super('invalid-phone-format', 'Exception.InvalidPhoneNumberFormat'.hardcoded, AlertWidgetType.snack);
}

class SmsVerificationFailedException extends AppException {
  SmsVerificationFailedException()
      : super('sms-verification-failed', 'Exception.SmsVerificationFailed'.hardcoded, AlertWidgetType.dialog);
}

class ProfileUpdateErrorException extends AppException {
  ProfileUpdateErrorException()
      : super('profile-update-error', 'Exception.ProfileUpdateError'.hardcoded, AlertWidgetType.dialog);
}