import 'package:soilreport/src/localization/localization_extension.dart';
import 'package:soilreport/src/localization/string_hardcoded.dart';

/// Base class for all all client-side errors that can be generated by the app

enum AlertWidgetType {
  dialog,
  snack
}

sealed class AppException implements Exception {
  AppException(this.code, this.message, this.type);
  final String code;
  final String message;
  final StackTrace stackTrace = StackTrace.current;
  final AlertWidgetType type;

  @override
  String toString() => message;
}

/// Auth

class PasswordNotMatchException extends AppException {

  PasswordNotMatchException()
      : super('password-not-match', 'Passwords don\'t match'.hardcoded, AlertWidgetType.snack);
}

class PasswordInvalidException extends AppException {

  PasswordInvalidException()
      : super('password-invalid', 'Password is not valid'.hardcoded, AlertWidgetType.snack);
}

class CouldntSetPasswordException extends AppException {

  CouldntSetPasswordException()
      : super('couldnt-set-password', 'Couldn\'t set password'.hardcoded, AlertWidgetType.snack);
}

class WrongPhoneNumberException extends AppException {
  WrongPhoneNumberException()
      : super('wrong-phone-number', 'wrong phone number'.hardcoded, AlertWidgetType.snack);
}
class WrongOtpException extends AppException {
  WrongOtpException()
      : super('wrong-otp', 'wrong otp'.hardcoded, AlertWidgetType.dialog);
}

class ClientStatsFetchFailedException extends AppException {
  ClientStatsFetchFailedException()
      : super('client-stats-fetch-failed', 'couldnt fetch client stats'.hardcoded, AlertWidgetType.dialog);
}
class UserNotFoundException extends AppException {
  UserNotFoundException() : super('user-not-found', 'User not found'.hardcoded, AlertWidgetType.dialog);
}

class NetworkIssueException extends AppException {
  NetworkIssueException() : super('network-issue', 'Network issue'.hardcoded, AlertWidgetType.snack);
}
class SystemErrorException extends AppException {
  final String? sysMessage;
  SystemErrorException({this.sysMessage}) : super("system-error-exception", sysMessage ?? 'system error'.hardcoded, AlertWidgetType.dialog);
}

class BiometricAuthenticationFailedException extends AppException {
    BiometricAuthenticationFailedException() : super("biometric-authentication-failed-exception", 'Common.Attempt.Unsuccessfully'.hardcoded, AlertWidgetType.snack);
}
class BiometricAuthenticationNotSupportedException extends AppException {
    BiometricAuthenticationNotSupportedException() : super("biometric-authentication-not-supported-exception", 'biometric authentication not supported'.hardcoded, AlertWidgetType.snack);
}

class JsonParseException extends AppException {
  JsonParseException() : super('json-parse', 'Couldnt parse json'.hardcoded, AlertWidgetType.dialog);
}

class ApiIssueException extends AppException {
  ApiIssueException() : super('api-issue', 'Didnt get proper response from api', AlertWidgetType.dialog);
}

class UnauthorizedUserException extends AppException {
  UnauthorizedUserException() : super('unauthorized-user', 'User unauthorized', AlertWidgetType.dialog);
}

/// Profile-specific exceptions
class EmptyEmailException extends AppException {
  EmptyEmailException()
      : super('empty-email', 'Email cannot be empty', AlertWidgetType.snack);
}

class InvalidEmailFormatException extends AppException {
  InvalidEmailFormatException()
      : super('invalid-email-format', 'Please enter a valid email address', AlertWidgetType.snack);
}

class EmailVerificationFailedException extends AppException {
  EmailVerificationFailedException()
      : super('email-verification-failed', 'Failed to send verification email. Please try again.', AlertWidgetType.dialog);
}

class EmptyPhoneNumberException extends AppException {
  EmptyPhoneNumberException()
      : super('empty-phone-number', 'Phone number cannot be empty', AlertWidgetType.snack);
}

class CantReachServerException extends AppException {
  CantReachServerException() : super('cant-reach-server', 'Auth.Alert'.hardcoded, AlertWidgetType.dialog);
}   

class NoInternetConnectionException extends AppException {
  NoInternetConnectionException() : super('no-internet-connection', 'Auth.Alert'.hardcoded, AlertWidgetType.snack);
}

class InvalidPhoneNumberFormatException extends AppException {
  InvalidPhoneNumberFormatException()
      : super('invalid-phone-format', 'Please enter a valid phone number', AlertWidgetType.snack);
}

class SmsVerificationFailedException extends AppException {
  SmsVerificationFailedException()
      : super('sms-verification-failed', 'Failed to send verification SMS. Please try again.', AlertWidgetType.dialog);
}

class ProfileUpdateErrorException extends AppException {
  ProfileUpdateErrorException()
      : super('profile-update-error', 'An error occurred while updating profile', AlertWidgetType.dialog);
}